base_url = "https://matling.fit"
title = "ç‰©çµ"

compile_sass = true

build_search_index = false

taxonomies = [
    {name = "tags", feed = true, paginate_by = 10},
]

[markdown]
highlight_theme = "boron-modified"
highlight_code = true
extra_syntaxes_and_themes = ["boron-modified.tmTheme"]

[translations]
language_name = "English"
toc = "Contents"
btn_read = "Read more (LEN words)"
higher = "Previous"
lower = "Next"
skip_link = "Skip to Content"
other_languages = "Translations"
backlinks = "Backlinks"

[languages.cmn]
title = "ç‰©çµ"

[languages.cmn-Arab]
title = "ç‰©çµ"

[languages.tok]
title = "ğ™[âŠ•ï¼Å„]"

[languages.ja]
title = "ç‰©éœŠ"

[languages.cmn.translations]
language_name = "åè¯­"
toc = "ç›®æ¬¡"
btn_read = "ç»­è¯» (LEN å­—)"
higher = "æ­¬"
lower = "å"
skip_link = "è·³è‡³æ­£æ–‡"
other_languages = "å¤–æ–‡"
backlinks = "é“¾å…¥"

[languages.cmn-Arab.translations]
language_name = "Ø¬à£¨Ù‰ÙÙˆÙ‹ Ø®ÙÙˆÙ"
toc = "Ù…ÙÙ„Ù"
btn_read = "Ú†ÙØ§Ù’Ø®Ø§ÙØ¯Ù (Ú©Ù’ Ù‰ÙÙˆ LEN Ø²)"
higher = "Ú†ÙÙ‰Ù‹"
lower = "Ø®ÙˆÙ’"
skip_link = "ØªÙÙ‰ÙÙˆÙ’ Ú©ÙÙ‰Ù’Ø´"
other_languages = "ÙˆÙÙ‰Ù„Ù Ù‡ÙÙˆÙ"
backlinks = "Ø²ÙÙ„ÙÙŠÙ’Ø¯Ù"

[languages.tok.translations]
language_name = "toki pona"
toc = "jo"
btn_read = "lipu ni (nimi LEN)"
higher = "pini"
lower = "kama"
skip_link = "tawa open lipu"
other_languages = "ante toki"
backlinks = "linja kama"

[languages.art-002.translations]
language_name = "Mini"
toc = "Peso"
btn_read = "Leje e mui (LEN name)"
higher = "ante"
lower = "afa"
skip_link = "go note-kapo"
other_languages = "Ota linga"
backlinks = "baka-liga"

[languages.art-001.translations]
language_name = "å˜äºœèª"
toc = "ç›®æ¬¡"
btn_read = "å…¨æ–‡ (LENå€‹ å­—)"
higher = "å‰"
lower = "å¾Œ"
skip_link = "æ–‡ç« ä¹‹é–‹å§‹äº"
other_languages = "å¤–æ–‡"
backlinks = "é€£å…¥"

[languages.ja.translations]
language_name = "æ—¥æœ¬èª"
toc = "ç›®æ¬¡"
btn_read = "å…¨æ–‡ (LEN å­—)"
higher = "å‰"
lower = "å¾Œ"
skip_link = "æœ¬æ–‡ã«ã‚¹ã‚­ãƒƒãƒ—"
other_languages = "å¤–æ–‡"
backlinks = "è¢«ãƒªãƒ³ã‚¯"

[extra]

[[extra.t2038.drawer_links]]
url = "/blog"

  [extra.t2038.drawer_links.name]
  cmn = "åšæ–‡"
  lzh = "åŸè‰"
  wuu = "æ­¥å½•"
  en = "Blog"
  tok = "lipu"
  dng = "Ğ—ÑƒÉ™Ğ²Ñ‹Ğ½"
  art-002 = "Note"
  art-001 = "æ–‡"
  cmn-Arab = "Ú¤ÙŒ"
  ja = "ãƒ–ãƒ­ã‚°"

[[extra.t2038.drawer_links]]
url = "https://lex.matling.fit"

  [extra.t2038.drawer_links.name]
  cmn = "å«ç« å­—å…¸"
  lzh = "å«ç« å­—å…¸"
  wuu = "å«ç« å­—å…¸"
  en = "Lexicon"
  tok = "nimi Malin"
  dng = "Ğ¥Ğ°Ğ½Ò—Ğ¾Ğ½ Ñ…ÑƒĞ°Ğ´ÑĞ½"
  art-002 = "Buku-name"
  art-001 = "å«ç« å­—å…¸"
  cmn-Arab = "Ø®Ù‹Ø¬Ù‹Ù†Ù’ ÙƒØªØ§Ø¨"
  ja = "å«ç« å­—å…¸"

[[extra.t2038.drawer_links]]
url = "/about/site"

  [extra.t2038.drawer_links.name]
  cmn = "å…³äº"
  lzh = "è‡ªæ•˜"
  wuu = "å…³äº"
  en = "About"
  tok = "mi seme"
  dng = "Ğ¡Ñ‹Ğ¹Ò—ÑĞ´Ğ¸"
  art-002 = "Ego"
  art-001 = "è‡ªå·±ç´¹ä»‹"
  cmn-Arab = "Ø£Ù†Ø§"
  ja = "ã‚¢ãƒã‚¦ãƒˆ"

[[extra.t2038.drawer_links]]
url = "/about/friends"

  [extra.t2038.drawer_links.name]
  cmn = "ä»–å±±"
  lzh = "è¨ªèˆŠ"
  wuu = "æœ‹å‹"
  en = "Friends"
  tok = "jan pona"
  dng = "Ğ¢Ğ°Ğ¼Ñ‹Ñ€"
  art-002 = "Amigo"
  art-001 = "å¤–éƒ¨"
  cmn-Arab = "Ø®ÙˆÙØ¨Ø§Ù‹"
  ja = "ãƒˆãƒŠãƒª"